
CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(75) NOT NULL UNIQUE,
	username VARCHAR(25) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	credits INTEGER NOT NULL DEFAULT 0,
	next_free_credit TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	activated BOOLEAN NOT NULL DEFAULT false
)
